### ISSUE TITLE
Use stricter type prechecks

### ISSUE THREAD

**Issue by pmstss** [NeuraLegion/har-sdk#115]
**Actual behavior**: 
* `mimeTypes.map is not a function` for non-array consumes value
* `x.trim is not a function` for non-string oas document title
* `x.trim is not a function` for non-string swagger host

**Expected behavior**: no exception

**Comment by pmstss** [comment]
similar no-prechecks case: `x.trim is not a function` for non-string oas document title

**Comment by derevnjuk** [comment]
There's exact the same issue while building URL: https://github.com/NeuraLegion/har-sdk/pull/112#discussion_r794856618
