### ISSUE TITLE
Optional security claims are not handled by convertor

### ISSUE THREAD

**Issue by brightAMasiuk** [NeuraLegion/har-sdk#167]
Conversion fails when the security requirement is optional or not exists in the `securitySchemes`

For provided schema with security `{}`:

```yaml
openapi: 3.0.1
info:
  title: Swagger Petstore
  version: 1.0.0
servers:
  - url: https://petstore.swagger.io
paths:
  /pets/security-empty
    get:
      security:
        - {}
      responses:
        200:
          description: Security empty
          content:
            application/json:
              schema: {}
components:
  securitySchemes:
    Bearer:
      type: http
      scheme: bearer
```
            
Converter output looks like this:  `Converter error: Cannot read properties of undefined (reading 'type')`

**Comment by derevnjuk** [comment]
@brightAMasiuk, please update the bug description to include the necessary information such as steps to reproduce, expected results, and actual results.

@BMNTeam @pmstss fyi

**Comment by brightAMasiuk** [comment]
**Steps:**

1.   Start scan
2.   Import the attached schema
3.   Check validation error

**Expected Result:**

 Schema parsed successfully

**Actual Result:**
 
 Converter error:

Cannot read properties of undefined (reading 'type')

**Comment by derevnjuk** [comment]
@brightAMasiuk the description is weakly formatted, senseless and useless. Which schema should I import and where? What does "run scan" mean in terms of the har-sdk and especially the oas package?

@BMNTeam @pmstss fyi
